[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "ejs", "morgan"]
  node_bundler = "esbuild"
  included_files = ["views/", "public/", "lib/**", "public/data/*.json"]


[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200


[[redirects]]
  from = "/lib/*"
  to = "/lib/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200