[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express", "ejs", "morgan", "supabase-js"]
  node_bundler = "esbuild"
  included_files = ["public/**", "lib/**", "public/data/*.json", "netlify/functions/views/**"]


[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/lib/*"
  to = "/lib/:splat"
  status = 200
  force = true

# Route other requests to Express
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/"
  status = 200